services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command:
      - postgres
      - "-c"
      - "max_connections=3000"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

  waha:
    image: devlikeapro/waha:latest
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - WHATSAPP_SESSIONS_POSTGRESQL_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      - WAHA_MEDIA_STORAGE=POSTGRESQL
      - WAHA_MEDIA_POSTGRESQL_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      - WAHA_API_KEY=1b4b5e0719254e3c905ae046449c5263
      - WAHA_DASHBOARD_USERNAME=admin
      - WAHA_DASHBOARD_PASSWORD=d22caa737b994b038aa5ddb1efd05fab
    depends_on:
      - postgres
    dns:
      - 1.1.1.1
      - 8.8.8.8
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/postgres
      - WAHA_API_URL=http://waha:3000
    volumes:
      - ./backend/app:/app/app
    depends_on:
      - postgres
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

volumes:
  postgres_data:
